world: world

islands:
  maps: 20
  startLength: 4
  endLength: 4
  spacing: 15

mode_distance: 1000

locations:
  spawn:
    x: 0.5
    y: 64
    z: 0.5
    yaw: 0
    pitch: 0
  pos1:
    x: 2.5
    y: 62
    z: -1.5
  pos2:
    x: -2.5
    y: 65
    z: 3.5

modes: {}
